import time


print("Hello world")
time.sleep(1)
print("Hello world")
time.sleep(1)
print("Hello world")
time.sleep(1)
print("Hello world")
time.sleep(1)
print("Hello world")
time.sleep(1)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")
time.sleep(10)
print("Hello world")

